import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { Container, Stack } from "@mui/material";
import { CreateStoreProfile } from "@/components/settings/CreateStoreProfile";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Stack bgcolor={"#F7F7F8"}>
        <Container sx={{ width: "1440px", height: "1024px" }}>
          <CreateStoreProfile />
        </Container>
      </Stack>
    </>
  );
}
